# Generated by Django 5.2.8 on 2025-11-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Action', '액션'), ('Comedy', '코미디'), ('Drama', '드라마'), ('Horror', '공포'), ('Romance', '로맨스'), ('Sci-Fi', 'SF'), ('Thriller', '스릴러')], max_length=50)),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
