# Generated by Django 5.2.4 on 2025-11-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('author', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
    ]
